/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingSubmission {
  'id' : string,
  'fullName' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'referenceFiles' : Array<ExternalBlob>,
  'phone' : [] | [string],
  'eventDate' : [] | [bigint],
  'eventType' : string,
}
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface GalleryItem {
  'id' : string,
  'title' : string,
  'videoLength' : [] | [bigint],
  'thumbnailUrl' : [] | [string],
  'tags' : Array<string>,
  'description' : string,
  'mediaUrl' : string,
  'seoKeywords' : Array<string>,
  'mediaType' : string,
  'category' : string,
  'uploadDate' : bigint,
  'altText' : string,
}
export interface Testimonial {
  'id' : string,
  'clientName' : string,
  'feedback' : string,
  'timestamp' : bigint,
  'eventType' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addGalleryItem' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      [] | [string],
      [] | [bigint],
      Array<string>,
      string,
      Array<string>,
    ],
    undefined
  >,
  'addTestimonial' : ActorMethod<[string, string, string, string], undefined>,
  'getAllBookingSubmissions' : ActorMethod<[], Array<BookingSubmission>>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getBookingSubmission' : ActorMethod<[string], BookingSubmission>,
  'getGalleryItemsByCategory' : ActorMethod<[string], Array<GalleryItem>>,
  'getGalleryItemsByTags' : ActorMethod<[Array<string>], Array<GalleryItem>>,
  'getMyContactSubmission' : ActorMethod<[], ContactSubmission>,
  'getTestimonial' : ActorMethod<[string], Testimonial>,
  'getTestimonialsByClientName' : ActorMethod<[string], Array<Testimonial>>,
  'submitBooking' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [string],
      string,
      [] | [bigint],
      string,
      Array<ExternalBlob>,
    ],
    undefined
  >,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];