/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const BookingSubmission = IDL.Record({
  'id' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'referenceFiles' : IDL.Vec(ExternalBlob),
  'phone' : IDL.Opt(IDL.Text),
  'eventDate' : IDL.Opt(IDL.Int),
  'eventType' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const GalleryItem = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'videoLength' : IDL.Opt(IDL.Nat),
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'mediaUrl' : IDL.Text,
  'seoKeywords' : IDL.Vec(IDL.Text),
  'mediaType' : IDL.Text,
  'category' : IDL.Text,
  'uploadDate' : IDL.Int,
  'altText' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Text,
  'clientName' : IDL.Text,
  'feedback' : IDL.Text,
  'timestamp' : IDL.Int,
  'eventType' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addGalleryItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'addTestimonial' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllBookingSubmissions' : IDL.Func(
      [],
      [IDL.Vec(BookingSubmission)],
      ['query'],
    ),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getBookingSubmission' : IDL.Func([IDL.Text], [BookingSubmission], ['query']),
  'getGalleryItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(GalleryItem)],
      ['query'],
    ),
  'getGalleryItemsByTags' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(GalleryItem)],
      ['query'],
    ),
  'getMyContactSubmission' : IDL.Func([], [ContactSubmission], ['query']),
  'getTestimonial' : IDL.Func([IDL.Text], [Testimonial], ['query']),
  'getTestimonialsByClientName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Testimonial)],
      ['query'],
    ),
  'submitBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Int),
        IDL.Text,
        IDL.Vec(ExternalBlob),
      ],
      [],
      [],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const BookingSubmission = IDL.Record({
    'id' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'referenceFiles' : IDL.Vec(ExternalBlob),
    'phone' : IDL.Opt(IDL.Text),
    'eventDate' : IDL.Opt(IDL.Int),
    'eventType' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const GalleryItem = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'videoLength' : IDL.Opt(IDL.Nat),
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'mediaUrl' : IDL.Text,
    'seoKeywords' : IDL.Vec(IDL.Text),
    'mediaType' : IDL.Text,
    'category' : IDL.Text,
    'uploadDate' : IDL.Int,
    'altText' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Text,
    'clientName' : IDL.Text,
    'feedback' : IDL.Text,
    'timestamp' : IDL.Int,
    'eventType' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addGalleryItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'addTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllBookingSubmissions' : IDL.Func(
        [],
        [IDL.Vec(BookingSubmission)],
        ['query'],
      ),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getBookingSubmission' : IDL.Func(
        [IDL.Text],
        [BookingSubmission],
        ['query'],
      ),
    'getGalleryItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GalleryItem)],
        ['query'],
      ),
    'getGalleryItemsByTags' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(GalleryItem)],
        ['query'],
      ),
    'getMyContactSubmission' : IDL.Func([], [ContactSubmission], ['query']),
    'getTestimonial' : IDL.Func([IDL.Text], [Testimonial], ['query']),
    'getTestimonialsByClientName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Testimonial)],
        ['query'],
      ),
    'submitBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Int),
          IDL.Text,
          IDL.Vec(ExternalBlob),
        ],
        [],
        [],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };